### ISSUE TITLE
Not able to scroll to the end of the story knobs when device keyboard is open

### ISSUE THREAD

**Issue by VinieSantana** [storybookjs/react-native#271]
When I try to edit a knob, the device keyboard overrides the end of the scroll view including the text field focused, if it's placed at the end of the list of knobs, and is not possible to scroll to the end of the content. 

I have the same behavior in both Android and iOS devices.

Current behavior:

![keyboard_issue](https://user-images.githubusercontent.com/14199109/134739037-d9a0876e-af22-475c-8968-a25c37cc3c22.gif)

Screen recorded from the Android Studio's Nexus 4 emulator with API 25

**Comment by dannyhw** [comment]
@VinieSantana thanks for reporting this I'll see if I can reproduce in the 6.0 controls tab and go from there

**Comment by dannyhw** [comment]
I think this is solved now in v6.5

**Comment by ghost** [comment]
This issue still exists on Android with the following storybook versions:

```
    "@storybook/addon-ondevice-actions": "^6.5.7",
    "@storybook/addon-ondevice-controls": "^6.5.7",
    "@storybook/addon-ondevice-notes": "^6.5.7",
    "@storybook/react-native": "^6.5.7",
```

[Android.webm](https://github.com/storybookjs/react-native/assets/67028082/1c386ebc-6c86-4055-967e-a5b6408dd331)

Video recorded on Pixel 2 API 30

**Comment by dannyhw** [comment]
@pbassi02 thanks I will take a look
